create table users(
    id bigint not null auto_increment,
	name varchar(100) not null,
    login varchar(100) not null,
	cellphone varchar(20) not null,
	email varchar(100),
	active boolean not null,
    password varchar(255) not null,    
    primary key(id)
);

CREATE TABLE userprofile(
	id bigint NOT NULL auto_increment,
	name varchar(255),
	description varchar(255),
	PRIMARY KEY (id)
);

CREATE TABLE users_userprofile(
	user_id bigint NOT NULL,
	userprofle_id bigint NOT NULL,	
	PRIMARY key(user_id, userprofle_id),
	CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id),
	CONSTRAINT fk_userprofile FOREIGN KEY (perfilusu_id) REFERENCES userprofile(id)
);create table userprofile (id bigint generated by default as identity, description varchar(255), name varchar(255) check (name in ('MANAGER','OPERATOR')), primary key (id));
create table users (active boolean, id bigint generated by default as identity, cellphone varchar(255), email varchar(255), login varchar(255), name varchar(255), password varchar(255), primary key (id));
create table users_userprofile (user_id bigint not null, userprofle_id bigint not null, primary key (user_id, userprofle_id));
alter table if exists users_userprofile add constraint FKg5msh7ub2bdphgfa6gnqv8y5c foreign key (userprofle_id) references userprofile;
alter table if exists users_userprofile add constraint FK8j09kvhlhohx4eofoiupfq57a foreign key (user_id) references users;
